sudo: enabled

language: python

python:
  - "3.6"

os:
  - linux

services:
  - mysql

# install dependencies
before_install:
  - mysql -e 'CREATE DATABASE test DEFAULT CHARSET utf8 COLLATE utf8_general_ci;'
  - mysql -e 'CREATE DATABASE dev DEFAULT CHARSET utf8 COLLATE utf8_general_ci;'

install:
  - pip3 install -r requirements.txt

before_script:
  - python manage.py gen_basic_data
  - python manage.py gen_fake_data

script:
  - coverage run --source=app manage.py test

after_success:
  - coveralls

notifications:
  email: false
